name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    env:
      BUILD_CFG_LOW_SPACE: "true"
      BUILD_CFG_BUILD_ALL_PACKAGES: "true"
    steps:
      - name: Display build env info
        run: |
          set -x
          df -h
          free -m
          nproc
          env
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: df -h
      - name: Prepare free space
        run: .github/scripts/prepare-free-space.sh
      - run: df -h
      - run: bin/build
      - run: df -h
      - name: Upload the artifacts
        run: .github/scripts/upload.sh "build/bin"
        env:
          GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
          GIT_PRIVATE_KEY: ${{ secrets.GIT_PRIVATE_KEY }}
      - run: df -h
