name: build

on:
  push:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    timeout-minutes: 600
    env:
      BUILD_CFG_LOW_SPACE: "true"
      BUILD_CFG_BUILD_ALL_PACKAGES: "true"
      BUILD_CFG_IGNORE_ERRORS: "true"
    steps:
      - name: Display build env info
        run: |
          set -x
          df -h
          free -m
          nproc
          env
      - name: Checkout
        run: |
          set -x
          mkdir -p "$GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE"
          git init .
          git remote add origin "https://github.com/$GITHUB_REPOSITORY.git"
          git config --local gc.auto 0
          git fetch --no-tags --depth=1 origin "$GITHUB_REF"
          git checkout -f -B build FETCH_HEAD
          git submodule sync --recursive
          git submodule foreach --recursive 'git config --local gc.auto 0'
          git submodule update --init --force --recursive --depth=1
      - run: df -h
      - name: Prepare free space
        run: .github/scripts/prepare-free-space.sh
      - run: df -h
      - run: bin/build
      - run: df -h
      - name: Upload the artifacts
        run: .github/scripts/upload.sh "build/bin"
        env:
          GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
          GIT_PRIVATE_KEY: ${{ secrets.GIT_PRIVATE_KEY }}
      - run: df -h
